// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakipAPI.Data;

#nullable disable

namespace StokTakipAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216092231_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StokTakipAPI.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalesHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oyuncu Laptopu",
                            PriceUsd = 1200m,
                            SalesHistory = "2,3,1,4,2,3,2",
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kablosuz Kulaklık",
                            PriceUsd = 150m,
                            SalesHistory = "1,2,0,1,2,1,1",
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Name = "Akıllı Saat",
                            PriceUsd = 250m,
                            SalesHistory = "5,4,6,5,4,5,5",
                            Stock = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
