// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakipAPI.Data;

#nullable disable

namespace StokTakipAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StokTakipAPI.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FiyatUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SatisGecmisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FiyatUsd = 1200m,
                            SatisGecmisi = "2,3,1,4,2,3,2",
                            Stok = 5,
                            UrunAdi = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            FiyatUsd = 150m,
                            SatisGecmisi = "1,2,0,1,2,1,1",
                            Stok = 100,
                            UrunAdi = "Kablosuz Kulaklık"
                        },
                        new
                        {
                            Id = 3,
                            FiyatUsd = 250m,
                            SatisGecmisi = "5,4,6,5,4,5,5",
                            Stok = 8,
                            UrunAdi = "Akıllı Saat"
                        },
                        new
                        {
                            Id = 4,
                            FiyatUsd = 150m,
                            SatisGecmisi = "5,3,10,1,3,2,2",
                            Stok = 26,
                            UrunAdi = "Klavye"
                        },
                        new
                        {
                            Id = 5,
                            FiyatUsd = 50m,
                            SatisGecmisi = "2,2,3,1,1,1,1",
                            Stok = 2,
                            UrunAdi = "Kablolu Kulaklık"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
